### ISSUE TITLE
Full path to the type used instead of the relative in the same package. Inertia.msg

### ISSUE THREAD

**Issue by zatevakhin** [ros2/common_interfaces#209]
The [Inertia.msg](https://github.com/ros2/common_interfaces/blob/rolling/geometry_msgs/msg/Inertia.msg#L5) uses `Vector3` with full path to type `geometry_msgs/Vector3`.

These two messages are in the same package. 
Should [Inertia.msg](https://github.com/ros2/common_interfaces/blob/rolling/geometry_msgs/msg/Inertia.msg#L5) use just `Vector3` instead of `geometry_msgs/Vector3`?

For the context:
We are working on a tool that translates ROS2 IDL messages to Python and generates package.
The abovementioned issue creates **circular import** because relative and absolute implications are mixed.

We handle this on our side by patching it as we think is correct using just `Vector3`.
If this is an issue we want to help by fixing this issue on the project side.

**Comment by clalancette** [comment]
While the extra namespace is probably unnecessary, I also don't think it is wrong.  That is, it should be fine to use either absolute or relative message names in other messages.  And it is clear that the ROS 2 tooling already does this (otherwise this wouldn't work).

I think your tool needs to know which package it is currently processing, and if it encounters absolute paths in them, just treat them as relative.

**Comment by zatevakhin** [comment]
Thanks! We will handle this on our side.
