### ISSUE TITLE
Feature: Add common set services for simple types

### ISSUE THREAD

**Issue by Hytac** [ros2/common_interfaces#224]
## Feature request
Implement set services for simple types such as int, float, string...

#### Feature description
In most cases is needed to set any of those simple types to a node. Seems a good approach to have them defined in std_srvs.

#### Implementation considerations
int32 data

bool success
string message

float32 data

bool success
string message

string data

bool success
string message

**Comment by clalancette** [comment]
This has come up many times in the past, and we've always said "no" to this feature request.

The basic reason is that ROS 2 is meant to be a strongly-typed system.  That actually means 2 things: that the types are well-defined (which they always are), but that they also have strong semantic meaning.  That is, an IMU message means that IMU data is in it.  A service message that is a generic `Int32` isn't strongly semantically typed, and it would be very difficult for producers to agree on what to produce, and for downstream consumers to know what semantics to expect from that piece of data.

Because of that, I'm going to close this one out.  Feel free to keep commenting if you'd like to discuss further.
